### ISSUE TITLE
Make contexts reactive

### ISSUE THREAD

**Issue by grischaerbe** [grischaerbe/threlte#1]
Currently, It's not possible to listen to camera changes or pointer position changes.

The proposed changes would change the `ThrelteContext` to this:

```ts
type ThrelteContext = {
  size: Writable<{ width: number; height: number }>
  pointer?: Writable<Vector2>
  clock: Clock
  camera?: Writable<Camera>
  scene: Scene
  renderer?: WebGLRenderer
  composer?: EffectComposer
  invalidate: (reason?: string) => void
}
```

So it's not the whole context that's a store but rather single properties. This makes it possible to destructure the result of `useThrelte` like `const { invalidate } = useThrelte()`.

But listening to camera changes would make HUD visibility and general UI work easier and more performant.

**Comment by Phenomen** [comment]
Same with <GLFT> url for model. It's not updated when model url is changed.
