### ISSUE TITLE
Svelte update broke threlte

### ISSUE THREAD

**Issue by 416d72** [grischaerbe/threlte#40]
Hi, just updated svelte and found this error:
```js
index.mjs:1857 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$$')
    at init (index.mjs:1857:50)
    at new Canvas (Canvas.svelte? [sm]:53:55)
    at createProxiedComponent (svelte-hooks.js:266:9)
    at new ProxyComponent (proxy.js:239:20)
    at new Proxy<Canvas> (proxy.js:346:11)
    at create_fragment (index.svelte? [sm]:32:40)
    at init (index.mjs:1877:37)
    at new Routes (index.svelte? [sm]:41:55)
    at createProxiedComponent (svelte-hooks.js:266:9)
    at new ProxyComponent (proxy.js:239:20)
```

My package.json

```json
"devDependencies": {
	"@sveltejs/adapter-auto": "next",
	"@sveltejs/kit": "next",
	"@types/three": "^0.137.0",
	"svelte": "^3.46.4",
	"svelte-check": "^2.4.5",
	"svelte-preprocess": "^4.10.4",
	"tslib": "^2.3.1",
	"typescript": "^4.5.5",
}
```

**Comment by grischaerbe** [comment]
Unfortunately I can't reproduce that. Can you maybe provide a test repo?

**Comment by 416d72** [comment]
> Unfortunately I can't reproduce that. Can you maybe provide a test repo?

[Here my web app](https://github.com/416d72/a3k.tech)

**Comment by grischaerbe** [comment]
Hm, it works for me. I guess I should've checked out the `main`. branch since you updated deps there?

**Comment by 416d72** [comment]
I've just created a whole new app and used the example you wrote in this README, and it works well even after running update.
So I have an issue with something else not this library.

Sorry for being idiot and opening an issue here without investigation, and wasting your time.

**Comment by grischaerbe** [comment]
No worries, all good 👍
