### ISSUE TITLE
Changing scene background?

### ISSUE THREAD

**Issue by garlandcrow** [grischaerbe/threlte#52]
I was evaluating threlte due to its more complete documentation vs SvelteCubed and I can't really figure out how I can set the background color of the scene. SvelteCubed exposes this as a prop on canvas, but then is setting the background of the scene with that prop. I can't seem to find how/where I can set props (like background color) on the scene in threlte. So maybe this can be made more clear in the docs?

**Comment by grischaerbe** [comment]
HI @garlandcrow, there's a discussion about changing the scene background: #31 
But I agree it could be an example in the docs. I'm currently working on a threlte website, so this is something that could be a part of it then.
