### ISSUE TITLE
Animated GLTF are not interactive!

### ISSUE THREAD

**Issue by 416d72** [grischaerbe/threlte#64]
Hello @grischaerbe , thanks for your amazing work.

I updated threlte to `3.6.1` and some animated GLTFs don't support interactivity!

I have two different model components [here](https://github.com/416d72/gltf-click/blob/master/src/routes/_path.svelte) and [here](https://github.com/416d72/gltf-click/blob/master/src/routes/_dummy.svelte), and a static model component [here](https://github.com/416d72/gltf-click/blob/master/src/routes/_duck.svelte)

The demo is [here](https://gltf-click.vercel.app/)

The cursor should be pointer when hovering over any model, but it doesn't! work for the animated ones!

**Comment by grischaerbe** [comment]
Hi @416d72!

Actually this is a limitation of three.js: Vertex transformations based on bones are happening are passed on to the vertex shader, they are running on the GPU so the CPU side (that's where raycasting is happening) of your application doesn't know the locations of the vertices nor is it able to compute proper bounding geometries. There are workarounds for that, see this stackoverflow issue: https://stackoverflow.com/questions/67481120/raycast-not-detecting-gltf-file-three-js

You can also use another invisible Mesh to raycast on:
```svelte title=Pathfinder.svelte
<script lang="ts">
  import { useGltfAnimations } from '$lib/useGltfAnimations'
  import { BoxBufferGeometry, MeshBasicMaterial } from 'three'
  import { GLTF, Group, Mesh, type Position, type Rotation, type Scale } from 'threlte'
  const { gltf, actions } = useGltfAnimations<'Confused'>()

  export let position: Position
  export let rotation: Rotation
  export let scale: Scale

  const triggerAnimation = () => {
    $actions['Confused']?.play()
  }

  const pointerenter = () => {
    document.body.style.cursor = 'pointer'
  }
  const pointerleave = () => {
    document.body.style.cursor = 'auto'
  }
</script>

<Group {position} {rotation} {scale}>
  <GLTF
    url={'/pathfinder.glb'}
    dracoDecoderPath="https://www.gstatic.com/draco/v1/decoders/"
    castShadow
    receiveShadow
    bind:gltf={$gltf}
  />

  <!-- If you plan on doing this for several objects, try to reuse geometry & material -->
  <Mesh
    interactive
    position={{ y: 1 }}
    on:click={triggerAnimation}
    on:pointerenter={pointerenter}
    on:pointerleave={pointerleave}
    geometry={new BoxBufferGeometry(0.6, 2, 0.7)}
    material={new MeshBasicMaterial()}
    visible={false}
  />
</Group>
```
So unfortunately there's nothing I can do. Hope this helps!

**Comment by 416d72** [comment]
Thanks again, I didn't know this was a limitation of three.js itself, I appreciate your workaround :)

**Comment by 416d72** [comment]
Update: I nearly succeeded in using the same model as a static mesh as you can view [here](https://gltf-click.vercel.app/) , but the only obstacle, is that the new mesh looks different from the original model in static mode!!

Here's the [relevant code](https://github.com/416d72/gltf-click/blob/master/src/routes/_path.svelte) , I'm almost certain this has nothing to do with three.js at all, but I don't know what should I look for !

**Comment by grischaerbe** [comment]
I'm not sure what the outcome should be but in terms of performance if it's solely to provide a click target I would just go for a single BoxBufferGeometry or a CapsuleGeometry. If it needs to be a bit more sophisticated you can add CapsuleGeometries to all bones.

**Comment by 416d72** [comment]
This may seem overkill, but I'd love to learn how to do something like object highlighting like in games.
