### ISSUE TITLE
threlte.xyz is DOWN

### ISSUE THREAD

**Issue by 416d72** [grischaerbe/threlte#65]
`error loading dynamically imported module`

**Comment by grischaerbe** [comment]
Hm, it's up on my end. Can you post the full error message and on what page/url you are getting this message? On which platform and browser?

**Comment by 416d72** [comment]
Sorry, I tested it again and it was down, but I tried disabling the adblock (ublock origin) and it works well now.

**Comment by 416d72** [comment]
It seems like ublock blocks this file `/_app/chunks/SocialLink-f4b9c5f4.js` !

**Comment by grischaerbe** [comment]
Ah interesting, this is an upstream problem. If you feel like you can issue it here: https://github.com/svelteness/kit-docs/blob/main/kit-docs
