### ISSUE TITLE
OBJ models load

### ISSUE THREAD

**Issue by Alersha** [grischaerbe/threlte#69]
hi, thanks for the brilliant work, tell pls if there are plans to add a similar GLTF, also an OBJ models?

**Comment by grischaerbe** [comment]
Hi @Alersha, no this is not planned. As glTF is currently the de-facto standard of importing and exporting 3D content from and to DCC apps like Blender or Cinema 4D i see no reason for OBJ to move forward. The last time I checked it's far too limited in terms of shader/material/textures compatibility and the tooling didn't get updates for quite some time. It took ages to establish glTF as the way to move forward and I'm super happy that we finally have a format that is as compatible as it is.
Contributions are always very welcome though, so if you feel like giving it a shot, feel free!

**Comment by Alersha** [comment]
thanks for the answer, yes glTF very modern and correct standard, but often in the work have to work with and obj files, in my opinion they have a small advantage in that they go immediately as one single mesh, convenient when you create your own scene directly in canvas

**Comment by grischaerbe** [comment]
I guess if you would use an object via a component `<OBJ>` you wouldn't notice a difference compared to `<GLTF>` in terms of the underlying file format structure, right? You can however load an OBJ with `const objLoader = useLoader(OBJLoader, () => new OBJLoader)` and use it in a `<MeshInstance mesh={loadedObj}>` component.
