### ISSUE TITLE
Algolia API key is public

### ISSUE THREAD

**Issue by dippa-1** [grischaerbe/threlte#73]
Is this on purpose? Or do you just not care (I mean I don't care either I just noticed it)

https://github.com/grischaerbe/threlte/blob/61f7574014e2056b1f03bfda82457198460acb07/src/routes/docs/__layout.svelte#L55

**Comment by grischaerbe** [comment]
Hey @dippa-1, this is meant to be public as this is a public-facing read-only API. Thanks for pointing that out nevertheless! 👍
