### ISSUE TITLE
Useframe causes error:=Unrecoverable HMR error in <Three>=

### ISSUE THREAD

**Issue by silveltman** [grischaerbe/threlte#74]
First of all, really well made plugin and docs!

I am experiencing issues with the useFrame hook. Error:
`[HMR][Svelte] Unrecoverable HMR error in <Three>: next update will trigger a full reload`

I got this when trying to make my mesh rotate. Howver, I found that a function like this gives the same error:
```
    useFrame(() => {
      console.log('frame')
    })
```

In case it's useful, here's my complete component:
```
<script>
  import { SphereGeometry, MeshStandardMaterial } from 'three'
  import {
    AmbientLight,
    Canvas,
    Mesh,
    PerspectiveCamera,
    PointLight,
    useTexture,
    useFrame,
  } from 'threlte'

  const geometry = new SphereGeometry(1, 32, 32)
  let rotation = {
    x: 0,
    y: 0,
    z: 0,
  }

  const textures = useTexture({
    map: '/assets/img/maps/colorMap.jpg',
    normalMap: '/assets/img/maps/NormalMap.jpg',
    roughnessMap: '/assets/img/maps/RougnessMap.jpg',
    displacementMap: '/assets/img/maps/DisplacementMap.jpg',
  })
  const material = new MeshStandardMaterial({ ...textures })
  material.displacementScale = 0.02

  useFrame(() => {
    console.log('frame')
  })
</script>

<div class="w-1/2 aspect-1">
  <Canvas>
    <PerspectiveCamera position={{ x: 0, y: 0, z: 2.4 }}>
      <!-- <OrbitControls autoRotate /> -->
    </PerspectiveCamera>

    <PointLight position={{ x: 50, y: 40, z: 50 }} intensity={0.5} />
    <AmbientLight color={0x0d1321} />

    <Mesh {geometry} {material} {rotation} />
  </Canvas>
</div>
```

**Comment by grischaerbe** [comment]
Hi @silveltman,

The docs definitely need to be more clear about this, but here's the relevant part: There are hooks that rely on the [context](https://svelte.dev/tutorial/context-api) provided by the `<Canvas>` component, see [the docs](https://threlte.xyz/docs/components/01-canvas) for details. All hooks that do so are marked with a box that says so.

Hope that helps!

**Comment by grischaerbe** [comment]
If you look at the code of a lot (all?) examples, you see there's a Wrapper.svelte component that is just wrapping the whole scene and its logic so that you don't need to worry about context.

**Comment by grischaerbe** [comment]
> Also, any wya to support hot module replacement (HRM)?

HMR should work out of the box, at least it does so for regular SvelteKit.

**Comment by silveltman** [comment]
That did the trick, thanks! 

Also fixed my color issue https://github.com/grischaerbe/threlte/issues/75#issuecomment-1175564163
