### ISSUE TITLE
Textureloader color way too light

### ISSUE THREAD

**Issue by silveltman** [grischaerbe/threlte#75]
I'm using the texture loader to load a map on a sphrere. Using this plugin it looks completely different than when I make the same thing on https://threejs.org/editor/ . It's just way lighter than the original image I use for my map. 

This is supposed to happen:
![image](https://user-images.githubusercontent.com/52583398/177413108-20bb89ff-03b6-416f-9557-f6f23950c90b.png)

this happens:
![image](https://user-images.githubusercontent.com/52583398/177413207-fb7c17cc-bcce-43e5-83b2-add3c9250913.png)

My component:
```
<script>
  import { MeshStandardMaterial, SphereGeometry } from 'three'
  import {
    PointLight,
    Canvas,
    Mesh,
    PerspectiveCamera,
    useTexture,
  } from 'threlte'

  const texture = useTexture('/assets/img/maps/ColorMap.jpg')
  const material = new MeshStandardMaterial({ map: texture })
</script>

<div>
  <Canvas>
    <PerspectiveCamera position={{ x: 0, y: 0, z: 3 }} />
    <PointLight intensity={0.9} position={{ x: 3, y: 10, z: 10 }} />
    <Mesh geometry={new SphereGeometry(1, 64, 64)} {material} />
  </Canvas>
</div>
```

Would really appreciate the help :)

**Comment by grischaerbe** [comment]
Hey @silveltman,

Yes, threlte is doing some color management in the same way as react-three-fiber *did*. The way [color management](https://threejs.org/docs/#manual/en/introduction/Color-management) works in three.js actually changed just recently (2 weeks ago? something like that) and the new way of color management is opt-in in vanilla three.js and on by default in react-three-fiber, it is not yet the default in threlte but it's in the making.

The main part about color mangement that Threlte does right now is this:
```ts
export const setRendererColorOutput = (
  ctx: ThrelteContext,
  linear: boolean,
  flat: boolean
): void => {
  if (!ctx.renderer) return
  if (linear) {
    ctx.renderer.outputEncoding = LinearEncoding
  } else {
    ctx.renderer.outputEncoding = sRGBEncoding
  }
  if (flat) {
    ctx.renderer.toneMapping = NoToneMapping
  } else {
    ctx.renderer.toneMapping = ACESFilmicToneMapping
  }
}
```
where linear and flat are properties on the <Canvas> component.

Currently, threlte follows [this guide](https://www.donmccurdy.com/2020/06/17/color-management-in-threejs/) on color management.

In your specific example, the hook `useTexture` is not able to infer the color management used in the `<Canvas>` component as it's not used in a child component to it and therefore hasn't access to its context. It's therefore not setting the encoding of the texture at all.

Hope that helps!

By the way, #57 will be tracking the progress on color management.

**Comment by silveltman** [comment]
@grischaerbe Thanks for the quick and clear answer!

However, with my lack of knowledge on this topic, your answer doesn't bring a solution to my mind.

How could I fix this problem in my case? The image that I use as a map is specifically made/chosen to fit the color-scheme of my site, so this is quite a problem for me...

Thanks in advance!

**Comment by silveltman** [comment]
Fixed thanks to https://github.com/grischaerbe/threlte/issues/74
