### ISSUE TITLE
ERR_MODULE_NOT_FOUND when building static app

### ISSUE THREAD

**Issue by richiejp** [grischaerbe/threlte#8]
Hi,

I found when trying to build my threlte based app for static deployment that I got an error similar to the following: `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<...>/node_modules/three/examples/jsm/postprocessing/EffectComposer' imported from <...>/.svelte-kit/output/server/entries/pages/index.svelte.js
Did you mean to import three/examples/jsm/postprocessing/EffectComposer.js?`

I saw that in threlte's svelte.config.js there are some extra vite options for threejs. It seems that adding the following "fixes" the issue:

```js
		  ssr: {
		    noExternal: ['three']
		  }
```

However then `index.svelte.js` balloons to 1105.56KiB from 63.85KiB. This is not a big deal IMO. However are there any plans/ideas to fix this?

**Comment by grischaerbe** [comment]
three.js in its nature is apparently [hard to treehshake](https://github.com/mrdoob/three.js/issues/17482). You could try using this plugin for vite to minify three.js: https://github.com/yushijinhun/three-minifier.
Let me know if it works, that would be great!

**Comment by richiejp** [comment]
Thanks, it seems to work, I still need to mark threejs as `noExternal`, however during the build it now says the `index.svelte.js` is  301.93KiB. The end result is this removes about 200KiB from the uncompressed JS.

**Comment by grischaerbe** [comment]
Thanks! I'll update the Docs accordingly!

**Comment by grischaerbe** [comment]
@richiejp Do you think [that's sufficient](https://github.com/grischaerbe/threlte#getting-started)? I saw that svelte-cubed also excludes three.js from vites optimization step, not sure if that is necessary. Do you have any insights on that?

**Comment by richiejp** [comment]
FWIW I think so. I'm not sure what these things do though.

-- 
  Richard Palethorpe
  ***@***.***
