### ISSUE TITLE
Pass having no effect

### ISSUE THREAD

**Issue by connercsbn** [grischaerbe/threlte#9]
Adding a glitch pass to the basic scene in your guide doesn't seem to work, possibly as a result of this line being deleted in ea2f5bfd106eca18452129675cc9a092d35d76d1:
```
ctx.composer.addPass(new RenderPass(ctx.scene, ctx.camera ?? new Camera()))
```
The pass works when I reintroduce the line on lib/renderer right after ```ctx.composer = new EffectComposer(ctx.renderer);```

**Comment by grischaerbe** [comment]
Uh, thank you! I must have missed that. I'll make a release by tomorrow.
